spring:
  application:
    name: order
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/order

rest-client:
  product:
    url: http://localhost:8081/api/v1/product
  customer:
    url: http://localhost:8082/customer

kafka:
  topic:
    order-receiver:
      name: orderReceiver
      partition: 0