spring:
  kafka:
    bootstrap-servers: http://localhost:9092
  application:
    name: order
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/order

rest-client:
  product:
    url: http://localhost:8081/api/v1/product
  customer:
    url: http://localhost:8082/api/v1/customer
  stock:
    url: http://localhost:8083/api/v1/stock

kafka:
  topic:
    order-receiver:
      name: orderReceiver
      partition: 0